name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kaniko
        uses: docker://gcr.io/kaniko-project/executor:v1.23.0-debug
        with:
          args: |
            --context /workspace --dockerfile /workspace/Dockerfile --destination docker.io/pifaqorik/kaniko-test:latest
        env:
          DOCKER_CONFIG: /kaniko/.docker
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Authenticate to Docker Hub
        run: echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"${{ secrets.DOCKER_USERNAME }}\",\"password\":\"${{ secrets.DOCKER_PASSWORD }}\"}}}" > /kaniko/.docker/config.json

      - name: Build and Push Docker image
        run: |
          /kaniko/executor --context /workspace --dockerfile /workspace/Dockerfile --destination docker.io/pifaqorik/kaniko-test:latest
