name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kaniko
        uses: google-github-actions/setup-kaniko@v1
        with:
          version: v1.23.2

      - name: Authenticate to Docker Hub
        run: echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"pifaqorik\",\"password\":\"killernoob007\"}}}" > /kaniko/.docker/config.json

      - name: Build and Push Docker image
        run: |
          /kaniko/executor --context . --dockerfile ./Dockerfile --destination docker.io/pifaqorik/kaniko-test:latest
